{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "newapi-risk-gateway.secretName" . }}
  labels:
    {{- include "newapi-risk-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if and (not .Values.kafkaTLS.existingSecret) (or .Values.kafkaTLS.caPem .Values.kafkaTLS.clientCertPem .Values.kafkaTLS.clientKeyPem) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "newapi-risk-gateway.kafkaTLSSecretName" . }}
  labels:
    {{- include "newapi-risk-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.pem: {{ .Values.kafkaTLS.caPem | quote }}
  client.pem: {{ .Values.kafkaTLS.clientCertPem | quote }}
  client-key.pem: {{ .Values.kafkaTLS.clientKeyPem | quote }}
{{- end }}
